name: Generate PR Summary

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate_pr_summary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Generate PR Summary
      run: |
        npm install -g conventional-pr
        conventional-pr --path . --output pr_summary.txt
    - name: Add PR Comment
      run: |
        COMMENT=$(cat pr_summary.txt)
        gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"